# Site settings
title:          Mateus Almeida
description:    "Meu Portf√≥lio"
url:            "https://imsouza.github.io"

# Google Analytics
google_analytics: G-P9G89F6KLE

# Author
author:
  name:         Mateus Almeida
  url:          https://imsouza.github.io
  email:        mateusalmeida0715@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      posts/:title
paginate:       999

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

collections:
  notas:
    output: true
    permalink: notas/:title/
